apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"ue-embb","slice-type":"embb"},"name":"ue-embb","namespace":"nexslice"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"ue-embb"}},"template":{"metadata":{"labels":{"app":"ue-embb","slice-type":"embb"}},"spec":{"containers":[{"command":["/opt/oai-nr-ue/bin/nr-uesoftmodem","-O","/opt/oai-nr-ue/etc/ue.conf","--rfsim","-r","106","--numerology","1","-C","3619200000","--ssb","516","--rfsimulator.serveraddr","oranslice-gnb"],"image":"docker.io/oaisoftwarealliance/oai-nr-ue:2025.w18","imagePullPolicy":"IfNotPresent","name":"nr-ue","resources":{"limits":{"cpu":"1000m","memory":"2Gi"},"requests":{"cpu":"500m","memory":"1Gi"}},"securityContext":{"privileged":true},"volumeMounts":[{"mountPath":"/opt/oai-nr-ue/etc/ue.conf","name":"ue-config","subPath":"ue.conf"}]}],"volumes":[{"configMap":{"name":"ue-embb-config"},"name":"ue-config"}]}}}}
  creationTimestamp: "2025-11-29T14:45:24Z"
  generation: 1
  labels:
    app: ue-embb
    slice-type: embb
  name: ue-embb
  namespace: nexslice
  resourceVersion: "43530"
  uid: 4e7dfd03-c862-41e5-98a7-a5a885252a3b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ue-embb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ue-embb
        slice-type: embb
    spec:
      containers:
      - command:
        - /opt/oai-nr-ue/bin/nr-uesoftmodem
        - -O
        - /opt/oai-nr-ue/etc/ue.conf
        - --sa
        - --rfsim
        - -r
        - "106"
        - --numerology
        - "1"
        - -C
        - "3619200000"
        - --ssb
        - "516"
        - --rfsimulator.serveraddr
        - oranslice-gnb
        image: docker.io/oaisoftwarealliance/oai-nr-ue:2025.w18
        imagePullPolicy: IfNotPresent
        name: nr-ue
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/oai-nr-ue/etc/ue.conf
          name: ue-config
          subPath: ue.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: ue-embb-config
        name: ue-config
status:
  conditions:
  - lastTransitionTime: "2025-11-29T14:45:24Z"
    lastUpdateTime: "2025-11-29T14:45:26Z"
    message: ReplicaSet "ue-embb-57d8cc99fd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-11-29T14:53:38Z"
    lastUpdateTime: "2025-11-29T14:53:38Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
