apiVersion: v2
name: oai-nr-ue3
description: Helm chart for OAI NR UE3 (Slice 3 - mMTC)
type: application
version: 2.1.0
appVersion: "2.1.0"
keywords:
  - OAI
  - NR-UE
  - 5G
  - mMTC
  - Slice3
home: https://gitlab.eurecom.fr/oai/openairinterface5g
sources:
  - https://gitlab.eurecom.fr/oai/openairinterface5g
maintainers:
  - name: NexSlice
